l# Databricks notebook source
# MAGIC %md
# MAGIC ## Pipeline Restaurante: Silver para Gold
# MAGIC 
# MAGIC Criando o modelo dimensional (Star Schema) com dimensões e fatos a partir da camada Silver.

# COMMAND ----------

# MAGIC %md ### 1. Leitura das Tabelas da Camada Silver

# COMMAND ----------

df_franquias = spark.read.format("delta").table("silver.franquias")
df_profissionais = spark.read.format("delta").table("silver.profissionais")
df_cardapio = spark.read.format("delta").table("silver.cardapio")
df_vendas = spark.read.format("delta").table("silver.vendas")

# Criando Temp Views para usar SQL
df_franquias.createOrReplaceTempView("franquias_silver")
df_profissionais.createOrReplaceTempView("profissionais_silver")
df_cardapio.createOrReplaceTempView("cardapio_silver")
df_vendas.createOrReplaceTempView("vendas_silver")

# COMMAND ----------

# MAGIC %md ### 2. Criação das Tabelas de Dimensão (DIM)

# COMMAND ----------

# MAGIC %sql
# MAGIC -- DIM_FRANQUIA
# MAGIC CREATE OR REPLACE TABLE gold.dim_franquia (
# MAGIC   SK_FRANQUIA         BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   NOME_FRANQUIA       STRING,
# MAGIC   CIDADE              STRING,
# MAGIC   ESTADO              STRING
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC -- DIM_PROFISSIONAL
# MAGIC CREATE OR REPLACE TABLE gold.dim_profissional (
# MAGIC   SK_PROFISSIONAL     BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   NOME_PROFISSIONAL   STRING,
# MAGIC   CARGO               STRING
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC -- DIM_CARDAPIO
# MAGIC CREATE OR REPLACE TABLE gold.dim_cardapio (
# MAGIC   SK_PRATO           BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   NOME_PRATO         STRING,
# MAGIC   PRECO              DECIMAL(10, 2),
# MAGIC   CATEGORIA          STRING
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC -- DIM_TEMPO (pode ser reutilizada de outros projetos ou criada)
# MAGIC CREATE OR REPLACE TABLE gold.dim_tempo
# MAGIC AS SELECT
# MAGIC   date_format(sequence.DATE, "yyyyMMdd") as SK_TEMPO,
# MAGIC   sequence.DATE as DATA,
# MAGIC   year(sequence.DATE) as ANO,
# MAGIC   month(sequence.DATE) as MES,
# MAGIC   day(sequence.DATE) as DIA,
# MAGIC   dayofweek(sequence.DATE) as DIA_DA_SEMANA
# MAGIC FROM (
# MAGIC   SELECT explode(sequence(to_date('2023-01-01'), to_date('2026-12-31'), interval 1 day)) as DATE
# MAGIC ) sequence;

# COMMAND ----------

# MAGIC %md ### 3. Carga das Dimensões (SCD Tipo 1 com MERGE)

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Carga da DIM_FRANQUIA
# MAGIC MERGE INTO gold.dim_franquia AS target
# MAGIC USING (SELECT SK_FRANQUIA AS ID_ORIGEM, NOME_FRANQUIA, CIDADE, ESTADO FROM franquias_silver) AS source
# MAGIC ON target.SK_FRANQUIA = source.ID_ORIGEM
# MAGIC WHEN MATCHED THEN
# MAGIC   UPDATE SET
# MAGIC     target.NOME_FRANQUIA = source.NOME_FRANQUIA,
# MAGIC     target.CIDADE = source.CIDADE,
# MAGIC     target.ESTADO = source.ESTADO
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (SK_FRANQUIA, NOME_FRANQUIA, CIDADE, ESTADO)
# MAGIC   VALUES (source.ID_ORIGEM, source.NOME_FRANQUIA, source.CIDADE, source.ESTADO);
# MAGIC 
# MAGIC -- Carga da DIM_PROFISSIONAL
# MAGIC MERGE INTO gold.dim_profissional AS target
# MAGIC USING (SELECT SK_PROFISSIONAL AS ID_ORIGEM, NOME_PROFISSIONAL, CARGO FROM profissionais_silver) AS source
# MAGIC ON target.SK_PROFISSIONAL = source.ID_ORIGEM
# MAGIC WHEN MATCHED THEN
# MAGIC   UPDATE SET
# MAGIC     target.NOME_PROFISSIONAL = source.NOME_PROFISSIONAL,
# MAGIC     target.CARGO = source.CARGO
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (SK_PROFISSIONAL, NOME_PROFISSIONAL, CARGO)
# MAGIC   VALUES (source.ID_ORIGEM, source.NOME_PROFISSIONAL, source.CARGO);
# MAGIC 
# MAGIC -- Carga da DIM_CARDAPIO
# MAGIC MERGE INTO gold.dim_cardapio AS target
# MAGIC USING (SELECT SK_PRATO AS ID_ORIGEM, NOME_PRATO, PRECO, CATEGORIA FROM cardapio_silver) AS source
# MAGIC ON target.SK_PRATO = source.ID_ORIGEM
# MAGIC WHEN MATCHED THEN
# MAGIC   UPDATE SET
# MAGIC     target.NOME_PRATO = source.NOME_PRATO,
# MAGIC     target.PRECO = source.PRECO,
# MAGIC     target.CATEGORIA = source.CATEGORIA
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (SK_PRATO, NOME_PRATO, PRECO, CATEGORIA)
# MAGIC   VALUES (source.ID_ORIGEM, source.NOME_PRATO, source.PRECO, source.CATEGORIA);

# COMMAND ----------

# MAGIC %md ### 4. Criação e Carga da Tabela Fato (FATO_VENDAS)

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Criação da tabela FATO
# MAGIC CREATE OR REPLACE TABLE gold.fato_vendas (
# MAGIC   SK_VENDA            BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   FK_FRANQUIA         BIGINT,
# MAGIC   FK_PROFISSIONAL     BIGINT,
# MAGIC   FK_PRATO            BIGINT,
# MAGIC   FK_TEMPO            INT,
# MAGIC   QUANTIDADE          INT,
# MAGIC   VALOR_TOTAL         DECIMAL(10, 2)
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Carga da FATO_VENDAS
# MAGIC -- Limpa a tabela fato para garantir a recarga completa (estratégia de recarga)
# MAGIC TRUNCATE TABLE gold.fato_vendas;
# MAGIC 
# MAGIC INSERT INTO gold.fato_vendas (FK_FRANQUIA, FK_PROFISSIONAL, FK_PRATO, FK_TEMPO, QUANTIDADE, VALOR_TOTAL)
# MAGIC SELECT
# MAGIC   v.SK_FRANQUIA,
# MAGIC   v.SK_PROFISSIONAL,
# MAGIC   v.SK_PRATO,
# MAGIC   t.SK_TEMPO,
# MAGIC   v.QUANTIDADE,
# MAGIC   v.VALOR_TOTAL
# MAGIC FROM vendas_silver v
# MAGIC JOIN gold.dim_tempo t ON v.DATA_VENDA = t.DATA;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.fato_vendas
# MAGIC LIMIT 10;